### ISSUE TITLE
./sspa server issue

### ISSUE THREAD

**Issue by bebekim** [benrady/learnjs#15]
I used git clone to copy to my local machine (ubuntu 14.04).
I am at learnjs root (young@young-PC:~/repository/js/learnjs in my machine) but I cannot start up sspa server.

```
young@young-PC:~/repository/js/learnjs$ ./sspa server
: No such file or directory
```

**Comment by benrady** [comment]
If you list the contents of the directory, what do you see?

**Comment by bebekim** [comment]
I see the following:

```
young@young-PC:~/repository/js/learnjs$ ls
conf  public  README.md  services  sspa  support
```

**Comment by benrady** [comment]
OK, I can see the sspa script there. What happens if you try to run it without any arguments?

**Comment by bebekim** [comment]
Nothing.

```
young@young-PC:~/repository/js/learnjs$ ls
conf  public  README.md  services  sspa  support
young@young-PC:~/repository/js/learnjs$ ./sspa
: No such file or directory
```

**Comment by benrady** [comment]
Maybe there's a problem with the shebang in the sspa script. What do the first few lines look like?

**Comment by bebekim** [comment]
```
#!/usr/bin/env bash

abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
root_dir=`dirname "$abspath"`
app_name=learnjs
code_bucket=${app_name}/_code_bundles
profile=admin
```

**Comment by benrady** [comment]
That looks correct. What happens when you run `/usr/bin/env bash`? Does it give you a prompt?

I'm trying to find what is giving you the "No such file or directory" error, because clearly the sspa script is there.

**Comment by bebekim** [comment]
I had reinstalled os and it's now working.
