### ISSUE TITLE
SSPA fails on an EC2 instance running the Amazon AMI

### ISSUE THREAD

**Issue by ghost** [benrady/learnjs#18]
I can't use my work laptop with your script. 
I have pre-existing development environments that are managed with Puppet and cannot be changed.
I cannot install npm, Python or Pip as required by your sspa script.

I have launched an EC2 instance with the Amazon AMI for this reason.

I could take a look at making changes to the SSPA script to accommodate individuals in a similar situation but wanted to check if I'm on the right track first.

Thanks.

**Comment by benrady** [comment]
Hmm. I'd be a little hesitant to change the SSPA script used by everyone to accommodate such a specific set of circumstances. Can you run docker? Or VirtualBox? That might be a way to create a virtual environment you can work in.

If you do find a solution that involves changing the script, I certainly don't mind hosting it on a branch.

**Comment by benrady** [comment]
Closing until a general solution can be found.
