### ISSUE TITLE
admin hardcoded in sspa script

### ISSUE THREAD

**Issue by cleesmith** [benrady/learnjs#20]
On lines 182 and 184 the sspa script has `--profile admin` instead of `--profile $profile`.
Also, would you consider covering more about python and boto3 ?
Thanks for writing the book.

**Comment by benrady** [comment]
Fixed in f6a00357511bc9e9b64213b266eca74cb0170f81.

Python and boto3 would make great topics for some blog posts. Will keep that in mind. Thanks!
