### ISSUE TITLE
sspa server command does not work with Python 3+

### ISSUE THREAD

**Issue by slq** [benrady/learnjs#25]
Having Python 3.5.2 I cannot run the follwing command
```
learnjs $ ​​./sspa​​ ​​server​
```
I get `python.exe: No module named SimpleHTTPServer`

I guess for Python 3+ 
```
python -m http.server
```
should be used instead.
Adding simple check to `sspa` script would be sufficient.

**Comment by benrady** [comment]
Fixed in #21
