### ISSUE TITLE
./sspa server requires AWS

### ISSUE THREAD

**Issue by gpellis** [benrady/learnjs#5]
Currently the code, in master (66ff4a7), and the book, version B1.0, don't line up. You're told to run `./sspa server` before you've set up your AWS config, but `sspa` now calls `check_aws` before it runs the server command, even though it doesn't really need it for the `server` command to succeed.

**Comment by benrady** [comment]
Fixed in 97f0c71a1b26a882395dbb26489744825f0b391e
