### ISSUE TITLE
Failed test once switched the ‘problemView’ implementation to use a template

### ISSUE THREAD

**Issue by rj74n6** [benrady/learnjs#6]
Two tests failed once I switched the 'problemView' implementation to use a template. In particular, they are:

```
it('can show a problem view', function() {
  learnjs.showView('#problem-1');
  expect($('.markup .problem-view').length).toEqual(1);
});
```

and

```
it('has a title that include the problem number', function() {
  var view = learnjs.problemView('1');
  expect(view.text()).toEqual("Problem #1 coming soon!")
})
```

The before and after code of problemView() are:

Chapter 2 'Loading the Application' page 39 

```
learnjs.problemView = function(problemNumber) {
  var title = 'Problem #' + problemNumber + ' Coming soon!';
  return $('<div class="problem-view">').text(title);
}
```

Chapter 3 'Essentials of Single Page Apps' page 50

```
 learnjs.problemView = function(problemNumber) {
   var view = $('.templates .problem-view').clone();
   view.find('.title').text('Problem #' + problemNumber);
   return view;
}
```

The app functions as intended. The problem seems to be the template based views were not put in the 'markup' div properly. Does it happen to other people too?

**Comment by benrady** [comment]
Do you have your app and tests deployed somewhere, so I can try this out?

**Comment by benrady** [comment]
I ask because there's some code in the spec helper that's supposed to do this, and I want to see how it's failing.

**Comment by rj74n6** [comment]
Hi Ben,

I have found the issue. It's my mistake: there was an un-matched html </div> and that was enough to confuse the javascript functions.

Thanks,
-Jerry

**Comment by benrady** [comment]
Glad you found it. Feel free to re-open this issue if you run into something related.
